language: c
script: ./.travis.sh
os:
    - linux
    - osx
env:
    - TARGET=host
    - TARGET=arm32
matrix:
    exclude:
        - os: osx
          env: TARGET=arm32
notifications:
    email: false
